### ISSUE TITLE
ADR: Front-end Code Quality Tools

### ISSUE THREAD

**Issue by widal001** [HHS/grants-equity#102]
### Description

Evaluate and select libraries to enforce the following standards within the frontend codebase:

- Dependency management (e.g. conflicts, updates, etc.)
- Code Linting
- Auto-formatting
- Type checking
- Checking for vulnerable dependencies
- Checking for open source licenses

### Definition of Done

- [ ] The approvers for this decision have been identified (ideally before work on the ADR starts)
- [ ] The ADR is created and stored in documentation/decisions/adr with status "Accepted"
- [ ] The ADR has been reviewed and approved by the approvers listed above
- [ ] The ADR satisfies requirements that are outlined in the ADR template
- [ ] Any follow-up tickets have been created (if necessary)
- [ ] The ADR covers each of the following tools:
  - [ ] Dependency management
  - [ ] Code linting
  - [ ] Auto-formatting
  - [ ] Type checking
  - [ ] Dependency vulnerability checking
  - [ ] License checking

**Comment by daphnegold** [comment]
Similar to back-end separation of concerns, suggesting we move testing and coverage tooling to a separate ADR
