### ISSUE TITLE
AWS Access

### ISSUE THREAD

**Issue by sumiat** [HHS/grants-equity#139]
- [ ] Provision and maintain AWS resources via Terraform IaC
- [ ] Configure AWS services (VPC, IAM, load balancers, security groups, Aurora RDS, Fargate, etc)
- [ ] Provision and manage external resources that interact with AWS (Github Actions CI/CD pipeline)
- [ ] Obtain domain name
- [ ] Configure, update, verify DNS settings
- [ ] Test and verify access

Users that will need access: @acouch, @daphnegold, @gcarson-bit, @SammySteiner (anyone I missed working on infra?)

**Comment by daphnegold** [comment]
Open Qs: 
- We will need access to MicroHealth AWS account, namely Aurora RDS to begin replication.
- What is the target AWS account we will be using? Does it exist yet?

**Comment by acouch** [comment]
We have been granted AWS access and have created users for the engineering team.
