### ISSUE TITLE
[ADR]: Branch conventions and release workflow

### ISSUE THREAD

**Issue by sumiat** [HHS/grants-equity#185]
### Description

This ADR will record the devision for branch naming conventions and release workflow. This may be combined with #112 , but it has been useful internally to treat them as separate tasks.

### Approvers

@acouch 
@widal001 
@daphnegold 
@lucasmbrown-usds (optional) 

### Definition of Done

- [ ] The approvers for this decision have been identified (ideally before work on the ADR starts)
- [ ] The ADR is created and stored in `documentation/decisions/adr` with status "Accepted"
- [ ] The ADR has been reviewed and approved by the approvers listed above
- [ ] The ADR satisfies requirements that are outlined in the ADR template
- [ ] Any follow-up tickets have been created (if necessary)

**Comment by lucasmbrown-usds** [comment]
Looks good! No need to include me for approval, but I might watch it go by.

**Comment by acouch** [comment]
We have discussed some of this internally.

ATM we are leaning toward (many of which we have been doing already):

* Git commit conventions decided here: https://github.com/HHS/grants-equity/issues/112
* Prefix the branch name with your name, and include the ticket number in the branch name e.g. `acouch/issue-1234-new-feature`
* Squash merge PRs
* PR Title:  “[Issue N] Short description”
* Ask for reviewer on team for PRs
* Merge own PR
* Start off with a trunk based development https://trunkbaseddevelopment.com/
* Use https://calver.org/ to version releases

Will draft an ADR ASAP.
