### ISSUE TITLE
[ADR]: Front-end deployment service

### ISSUE THREAD

**Issue by sumiat** [HHS/grants-equity#189]
### Description
Blocked by #222 
Decision record for the frontend deployment service

- Choosing between EC2 and Fargate for ECS cluster launch type; just EC2, using a lambda for frontend functions, and S3 buckets for frontend. 
- Beyond the CI/CD and cloud service we're using

### Approvers

Another engineer who is not working the ticket: @acouch @daphnegold @SammySteiner
@gcarson-bit (optional)
@widal001 (optional)
@lucasmbrown-usds (optional)

### Definition of Done

- [ ] The approvers for this decision have been identified (ideally before work on the ADR starts)
- [ ] The ADR is created and stored in `documentation/decisions/adr` with status "Accepted"
- [ ] The ADR has been reviewed and approved by the approvers listed above
- [ ] The ADR satisfies requirements that are outlined in the ADR template
- [ ] Any follow-up tickets have been created (if necessary)

**Comment by daphnegold** [comment]
Rolled into a single ADR with #187

**Comment by sumiat** [comment]
Merged with #187

**Comment by sumiat** [comment]
Added the comment above to close the ticket
