### ISSUE TITLE
[Task]: Content design draft for static beta site

### ISSUE THREAD

**Issue by andycochran** [HHS/grants-equity#219]
### Summary

Per info brainstormed in #106, draft a content strategy for a v0.0 of the static beta site that includes: 
- Information about the goals and structure of the NOFO simplification project
- Links to the four NOFO prototypes
- Information about how to sign up for future updates
- ~Information about upcoming events~ (do not yet exist) 

Information to be confirmed: 
- URI for survey (and whether the call-to-action should only be for applicants, not grantors)
- What's the preferred contact method for grantors at HHS or other grantmaking agencies to reach out — email, phone, specific point of contact?
- Can/should quotes from user research be included? 

### Acceptance criteria

- [x] Reviewed with @itsemilyianacone 
- [x] Reviewed with @lucasmbrown-usds 
- [x] Reviewed with and approved by Elizabeth 
- [x] Andy has synced with engineering team regarding implementation

**Comment by andycochran** [comment]
[In-progress Figma mockup](https://www.figma.com/file/lpKPdyTyLJB5JArxhGjJnE/beta.grants.gov?type=design&node-id=0-1&mode=design&t=HJkZ5GHbLVdUpAC5-0)

**Comment by sumiat** [comment]
- @andycochran created [Static site content doc](https://docs.google.com/document/d/16l2Gy-AstT9cgJK3jy_qe0I53nHhgri1O3F9UVc1TTU/edit#heading=h.syecbpqvccr6) and reviewed with Emily and Lucas.

**Comment by sumiat** [comment]
Closing, all have reviewed. Content updated with Robert's final edits in #405
