### ISSUE TITLE
[Task]: Reconfigure Github Actions CI/CD for mono-repo structure

### ISSUE THREAD

**Issue by daphnegold** [HHS/grants-equity#285]
### Summary

Blocked by  #139 
#299 #300 should be completed prior to this ticket (see below)

Note: Infrastructure + Github Actions should exist before this ticket can be worked on. This can be done in multiple ways, at the discretion of whoever picks up this issue:
1. Incrementally, in coordination and piecemeal as front-end or back-end infrastructure are set up
1. First either front-end or back-end is set up, then this is done in tandem with the remaining
1. As a fast follow up task after back-end and front-end infra, where CI/CD will not function as intended until this is completed

____

Template applications are meant to be in separate repositories. Some work needs to be done for the Github Actions to run appropriately in a mono-repo after template infra is implemented for both frontend and API. See links for more context.

https://github.com/navapbc/template-infra/issues/238
https://nava.slack.com/archives/C03G1SWD9H7/p1689363837120939

### Acceptance criteria

- [ ] Modify Github Actions workflows
- [ ] Test (I haven't tried this, but there are ways to run GA locally now, please report back how it goes!)

**Comment by SammySteiner** [comment]
Adding here so we don't forget, update inputs from type of string to choice wherever possible to reduce the chances of typos breaking things or things failing to run.
