### ISSUE TITLE
Task: Create Issue Templates

### ISSUE THREAD

**Issue by widal001** [HHS/grants-equity#31]
### Description

Create a series of issue templates that make it easier for users to create issues that follow a common structure and contain a minimum set of information needed to work on that issue.

### Specification

- Milestone Docs
  - **Label:** `docs: milestone`
  - **Description:** Draft a new milestone document
  - **Example:** [DB & API Planning](https://github.com/HHS/grants-api/issues/21)
  - **Sections**
    - **Description:** 1-2 sentence summary with link to short description 
    - **Definition of Done** (Prefilled with the following task list)
      - Milestone document is updated and stored in documents/milestones/individual_milestones/
      -  The milestone document has been linked under the appropriate section in the short description doc
      -  The milestone has node has been updated to "planning" in the dependency diagram
      -  Milestone has been reviewed and approved by the internal team
      -  A corresponding epic has been created for the milestone
- ADRs
  - **Label:** `docs: adr`
  - **Example:** [Wiki ADR](https://github.com/HHS/grants-api/issues/30)
  - **Description:** Record an architectural decision about the project
  - **Sections**
    - **Description:** Open text field for 1-2 sentence summary of the decision that needs to be made
    - **Options (Optional):** Open text field for list of options to evaluate
    - **Decision Criteria (Optional):** Open text field for list of decision criteria to evaluate
    - **Definition of Done** (Prefilled with the following task list)
      - The ADR is drafted and stored in documentation/[ADR folders TBD]/
      -  The ADR is included in the necessary table of contents in the ADR/decision folder
      -  The ADR describes the drivers and pros and cons of the decision
      -  The ADR has been reviewed and approved by the internal team
      -  The ADR satisfies requirements that are outlined in the ADR template

### Definition of Done

- [ ] Users are presented with a series of options when they create a new ticket
- [ ] When users select an issue type, they are prompted with a series of questions that help them build out the issue
- [ ] Issues are automatically labeled based on the issue type
- [ ] Users can edit or add to the resulting output generated from the form response

**Comment by daphnegold** [comment]
PR includes `adr` and `milestone` templates following the specifications above! I included links in the PR. @widal001 do you want to review the other templates for bugs, feature requests, etc together, or maybe just remove them from this PR/issue entirely and into another?

**Comment by daphnegold** [comment]
PR includes adr and milestone templates following the specifications above! I included links in the PR to try them out in my test repo. @widal001 how do you want to approach getting the other templates for bugs, feature requests, etc to a good state?
