### ISSUE TITLE
[ADR]: GitHub issues & project conventions

### ISSUE THREAD

**Issue by widal001** [HHS/grants-equity#320]
### Description

Create an ADR that documents answers the following questions about how we use GitHub Issues and GitHub Projects to manage and organize work within the project:

- GitHub Issue Questions
  - What types of issues should we create templates for?
  - What are the primary labels we want to use to organize tickets?
  - How do we plan to use milestones and task lists to organize tickets hierarchically?
  - When should PRs be attached to issues? To milestones?
- GitHub Project Questions
  - Do we want to use story points?
  - If so, what scale/intervals should we use for pointing tickets?
  - What are the primary views we want to support within GitHub projects?
  - What are the primary metrics we want to calculate with project data?

### Approvers

- @EOKENAVA 
- @sumiat 
- @widal001 
- @lucasmbrown-usds 
- @sarahknoppA6 

### Definition of Done

- [x] The approvers for this decision have been identified (ideally before work on the ADR starts)
- [x] This documentation has been added to GitBook
- [x] The ADR has been reviewed and approved by the approvers listed above

**Comment by widal001** [comment]
Work was started on this during the week of 9/4 but was paused due to higher priority items. This will carry over to the week of 9/11

**Comment by sumiat** [comment]
updated the internal wiki with github pages: [Main github](https://app.gitbook.com/o/cFcvhi6d0nlLyH2VzVgn/s/v1V0jIH7mb7Yb3jlNrgk/collaborating/how-we-communicate/github), [How we work](https://app.gitbook.com/o/cFcvhi6d0nlLyH2VzVgn/s/v1V0jIH7mb7Yb3jlNrgk/collaborating/how-we-communicate/github/how-we-work), and [Estimates and story pointing](https://app.gitbook.com/o/cFcvhi6d0nlLyH2VzVgn/s/v1V0jIH7mb7Yb3jlNrgk/collaborating/how-we-communicate/github/estimates-and-story-pointing). Posted in slack for review!
