### ISSUE TITLE
[ADR]: Replication tool

### ISSUE THREAD

**Issue by sumiat** [HHS/grants-equity#322]
### Description

We aim to decide on the most suitable replication tool for the transformation process. We could use AWS Data Migration but this ADR should evaluate if it is appropriate or if we should use an alternative tool. 

We need to determine whether an ETL pipeline is required for data transformation if the selected replication tool does not handle it inherently. 

### Approvers

- [ ] 1 engineer not on the ticket
- [ ] Billy Daly or Lucas Brown

### Decision Criteria

Decision criteria that could potentially impact the tool used: 

- **Data source and destination compatibility**: rep tool should support the data sources used in the project (db, file systems) and is compatible with the target destination (db, warehouses, cloud storage).
- **Data volume and throughput**: tool can handle the volume and throughput requirements of the data replication process efficiently.
- **Data transformation capabilities:** replication tool can handle data transformation during the replication process, including data format conversions and schema changes.
- **Real-time vs. batch replication**: determine whether real-time data replication or if batch replication at scheduled intervals is sufficient.
- **Latency and performance**: consider the latency and performance to ensure timely data updates and minimal impact on system performance.
- **Security and encryption**: replication tool provides adequate security features, including data encryption and secure data transmission.
- **Monitoring and alerting**: to promptly identify and address replication issues.
- **Ease of use and configuration**: Evaluate the tool's user-friendliness and ease of configuration, as complex setup processes can lead to inefficiencies.
- **Scalability**: Determine if the replication tool can scale to accommodate future growth and increased data demands.
- **Cost**: Consider the licensing and operational costs
- **Support and community**: Assess availability of support options and the size and activity of the tool's user community.

### Definition of Done

- [ ] The approvers for this decision have been identified (ideally before work on the ADR starts)
- [ ] The ADR is created and stored in `documentation/decisions/adr` with status "Accepted"
- [ ] The ADR has been reviewed and approved by the approvers listed above
- [ ] The ADR satisfies requirements that are outlined in the ADR template
- [ ] Any follow-up tickets have been created (if necessary)

**Comment by lgomez1111** [comment]
Got clarification on a few points, VPC peering, with only ports/protocols open necessary for AWS DMS, and for filesystem replication of application data such as RTD, for lower enviorment (Test Data). Agree with the approach, to move forward.
