### ISSUE TITLE
[Task]: Implement footer for static site

### ISSUE THREAD

**Issue by sumiat** [HHS/grants-equity#336]
### Summary

Now that the Front-end repo has been set up, we can use the template to start adding content for the future beta.grants.gov site. 
We ultimately want the design to match the [Figma mockup]

We are breaking up the work into components. This ticket focuses only on the footer of the content. 
![image](https://github.com/HHS/grants-equity/assets/111455374/e0cd15c3-6808-4057-b9a2-c929c4781840)

- Add the approved footer content changes to the page
- Ensure all the links and form on the page works as expected
- Following the USWDS style guide

### Links
* [Figma mockup](https://www.figma.com/file/lpKPdyTyLJB5JArxhGjJnE/beta.grants.gov?type=design&node-id=0-1&mode=design&t=781AdnK0dT5hXDxT-0)
* [Static site content](https://docs.google.com/document/d/16l2Gy-AstT9cgJK3jy_qe0I53nHhgri1O3F9UVc1TTU/edit#heading=h.syecbpqvccr6)
* HHS Logo https://www.hhs.gov/web/policies-and-standards/web-policies/logo-seal-and-symbol-policies/index.html
![HHS logo](https://github.com/HHS/grants-equity/assets/111455374/5ffc0675-3188-45b3-a869-38f0896581ab)
* Twitter Link: https://twitter.com/grantsdotgov
* Youtube link: https://www.youtube.com/user/GrantsGovUS
* RSS link: https://www.grants.gov/web/grants/rss.html
* Facebook link: there is no facebook link, this icon can be removed
* Instagram link: There is no instagram link, this icon can be removed. 
* Newsletter link: https://www.grants.gov/web/grants/connect/newsletter-archive.html 
* Blog link: https://grantsgovprod.wordpress.com/
* Phone number: 1-877-696-6775
* Email: [support@grants.gov](mailto:support@grants.gov)

### Acceptance criteria

- [ ] Footer is working and match the Figma design
- [ ] Appears as a story in Storybook
- [ ] Test coverage
- [ ] Static site content served from root of the application
- [ ] Updated content and design to match the [Figma mockup](https://www.figma.com/file/lpKPdyTyLJB5JArxhGjJnE/beta.grants.gov?type=design&node-id=0-1&mode=design&t=781AdnK0dT5hXDxT-0) 
- [ ] mobile formatting as expected
- [ ] desktop formatting as expected
- [ ] Accessibility testing (should be inherited when using USWDS)
- [ ] Approvers: at least one design or product person

### Dependencies
#283

**Comment by sumiat** [comment]
Hi @daphnegold - I updated the links. HHS does not have a facebook or instagram so we can remove those icons. They do have a newsletter and blog links. I added those but need to find the icons for those. Will update those when I get it but if you work on this ticket before I get those, no problem. I can create a separate ticket to add that later.

**Comment by andycochran** [comment]
Looked thru [the icon set](https://designsystem.digital.gov/components/icon/) to see what's most appropriate for those links. 

For newsletter, we can use the `mail` icon: 
![image](https://github.com/HHS/grants-equity/assets/409279/971a3f7d-832a-4b4f-8a4f-bcbb7de86321)

And for the bloc we can use… hmm… maybe `local_library` (it's a person reading, and I don't think it's an established symbol that can only mean "library"): 
![image](https://github.com/HHS/grants-equity/assets/409279/772a2d09-6c6a-40c4-a3e3-5e12f9d389dd)

**Comment by daphnegold** [comment]
The bigger issue here is the `SocialLink` component that does not allow for customization like that. It's locked to the presets. So we need to do our own custom thing here, a wrapper around `SocialLink` or something. See here: https://github.com/trussworks/react-uswds/blob/e1c60cbff90c484b1942675a459aaab2e581b0e1/src/components/Footer/SocialLinks/SocialLinks.tsx

Worth it, @andycochran or we put the links for newsletter and blog elsewhere?

**Comment by andycochran** [comment]
That's… disappointing. [USWDS guidance](https://designsystem.digital.gov/components/footer/) explicitly says: 

![image](https://github.com/HHS/grants-equity/assets/409279/d1996ba9-b7b4-48a0-b58b-3db9a24fbb8b)

So I'd have thought the `Footer` component would be more robust and flexible. The Truss components are there for convenience, and if they're not convenient… 

We can ignore the Truss `SocialLinks` component — or ignore any of the `Footer` subcomponents if they're insufficient — and just use the markup from the [USDWS Footer component](https://designsystem.digital.gov/components/footer/) directly. Let's just hardcode the footer if Truss components aren't working out-of-the-box. 

Any thoughts, @SammySteiner?

**Comment by daphnegold** [comment]
I can hack it by making my own `SocialLink` which is just an <a> tag with an icon! We good.
