### ISSUE TITLE
[Task]: Implement Hero for static site

### ISSUE THREAD

**Issue by SammySteiner** [HHS/grants-equity#359]
### Summary

Now that the Front-end repo has been set up, we can use the template to start adding content for the future beta.grants.gov site. 
We ultimately want the design to match the [Figma mockup](https://www.figma.com/file/lpKPdyTyLJB5JArxhGjJnE/beta.grants.gov?type=design&node-id=0-1&mode=design&t=781AdnK0dT5hXDxT-0)

We are breaking up the work into components. This ticket focuses only on the hero content. 
![image](https://github.com/HHS/grants-equity/assets/25465464/95ffea5e-743d-403c-bd77-67e40c5118b3)

- Add the approved hero content changes to the page
- Following the USWDS style guide

### Links
* [Figma mockup](https://www.figma.com/file/lpKPdyTyLJB5JArxhGjJnE/beta.grants.gov?type=design&node-id=0-1&mode=design&t=781AdnK0dT5hXDxT-0)
* [Static site content](https://docs.google.com/document/d/16l2Gy-AstT9cgJK3jy_qe0I53nHhgri1O3F9UVc1TTU/edit#heading=h.syecbpqvccr6)

### Acceptance criteria

- [ ] Hero is working and match the Figma design
- [ ] Appears as a story in Storybook
- [ ] Test coverage
- [ ] Static site content served from root of the application
- [ ] Updated content and design to match the [Figma mockup](https://www.figma.com/file/lpKPdyTyLJB5JArxhGjJnE/beta.grants.gov?type=design&node-id=0-1&mode=design&t=781AdnK0dT5hXDxT-0) 
- [ ] mobile formatting as expected
- [ ] desktop formatting as expected
- [ ] Accessibility testing (should be inherited when using USWDS)

### Dependencies
#283

**Comment by daphnegold** [comment]
The Hero component mentioned in the Landing Page link above doesn't exist anywhere in their component list on the USWDS site. Inspecting their example landing page, looks like there are some pre-defined classes to style a Hero though:

```html
<section class="usa-hero" aria-label="Introduction">
      <div class="grid-container">
        <div class="usa-hero__callout">
          <h1 class="usa-hero__heading">
            <span class="usa-hero__heading--alt">Hero callout:</span>Bring
            attention to a project priority
          </h1>
          <p>
            Support the callout with some short explanatory text. You don’t need
            more than a couple of sentences.
          </p>
          <a class="usa-button" href="">Call to action</a>
        </div>
      </div>
    </section>
```

**Comment by daphnegold** [comment]
USWDS design docs don't have a specific component listed for Hero. Their example site does have an implementation just using pre-defined classes. Our React USWDS library also does not have a Hero component we can consume. However, searching their repository, below is how they implement the Hero on their example landing page. 

```html
<section className="usa-hero" aria-label="Introduction">
  <GridContainer>
    <div className="usa-hero__callout">
      <h1 className="usa-hero__heading">
        <span className="usa-hero__heading--alt">Hero callout:</span>
        Bring attention to a project priority
      </h1>
      <p>
        Support the callout with some short explanatory text. You don’t
        need more than a couple of sentences.
      </p>
      <a className="usa-button" href="javascript:void(0)">
        Call to action
      </a>
    </div>
  </GridContainer>
</section>
```
