### ISSUE TITLE
[Task]: Implement the funding opportunity section for the static site

### ISSUE THREAD

**Issue by sumiat** [HHS/grants-equity#361]
### Summary

Now that the Front-end repo has been set up, we can use the template to start adding content for the future beta.grants.gov site. 
We ultimately want the design to match the [Figma mockup](https://www.figma.com/file/lpKPdyTyLJB5JArxhGjJnE/beta.grants.gov?type=design&node-id=0-1&mode=design&t=781AdnK0dT5hXDxT-0)

We are breaking up the work into components. This ticket focuses only on the funding opportunity section the content. 
![image](https://github.com/HHS/grants-equity/assets/111455374/04a696a6-0f1c-41ac-a56d-ee3f0c42faca)

- Add the approved funding opportunity content changes to the page
- Ensure all the links and form on the page works as expected
- Following the USWDS style guide

### Links
* [Figma mockup](https://www.figma.com/file/lpKPdyTyLJB5JArxhGjJnE/beta.grants.gov?type=design&node-id=0-1&mode=design&t=781AdnK0dT5hXDxT-0)
* [Static site content](https://docs.google.com/document/d/16l2Gy-AstT9cgJK3jy_qe0I53nHhgri1O3F9UVc1TTU/edit#heading=h.syecbpqvccr6)
* The the 4 nofo prototypes available here: https://github.com/HHS/grants-equity/tree/main/documentation/notice_of_funding_opportunity_prototypes (ACF, ACL, CDC, SAMHSA)
* The method for the feedback form is still TBD, if we have not decided on a method for collecting feedback at the time this ticket is picked up, we will not add the following section: 
![image](https://github.com/HHS/grants-equity/assets/111455374/c65a2731-ea79-42f9-9e62-672fbd8e6b29)

### Acceptance criteria

- [ ] Funding opportunity section is working and match the Figma design (Feedback form section is optional, depending on status)
- [ ] Test coverage
- [ ] Static site content served from root of the application
- [ ] Updated content and design to match the [Figma mockup](https://www.figma.com/file/lpKPdyTyLJB5JArxhGjJnE/beta.grants.gov?type=design&node-id=0-1&mode=design&t=781AdnK0dT5hXDxT-0) 
- [ ] mobile formatting as expected
- [ ] desktop formatting as expected
- [ ] Accessibility testing (should be inherited when using USWDS)

**Comment by andycochran** [comment]
| ACL | ACF | CDC | SAMHSA | 
| --- | --- | --- | --- | 
| ![image](https://github.com/HHS/grants-equity/assets/409279/9a0369aa-a84b-43e3-bb7e-c651071a250f) | ![image](https://github.com/HHS/grants-equity/assets/409279/24209cbc-ceb8-4a0d-ad7e-0aa259e00c5b) | ![image](https://github.com/HHS/grants-equity/assets/409279/792c7441-cd97-4abe-9fee-e94dd2e65d39) | ![image](https://github.com/HHS/grants-equity/assets/409279/451655d1-26ff-4102-af47-3490684ecc0c) |
