### ISSUE TITLE
[Task]: Research DMS as DB Replication Tool

### ISSUE THREAD

**Issue by gcarson-bit** [HHS/grants-equity#369]
### Summary

Evaluate the AWS Database Migration Service (DMS) feasibility as a potential solution for the Grants.gov DB replication.
Check that it meets the replication requirements:

- Can handle the size of the existing DB
- Can support data transformations
- Logging
- Cost
- FEDRAMP approved

### Acceptance criteria

DMS is evaluated and determined to be either feasible or not feasible as a potential solution for the Grants.gov DB replication.

**Comment by acouch** [comment]
This research has been completed.
