### ISSUE TITLE
[Task]: Update README with open source runbook content

### ISSUE THREAD

**Issue by sumiat** [HHS/grants-equity#402]
### Summary

The USDR team has provided [content in a runbook format ](https://docs.google.com/document/d/1CyoA57KejbNEGhaLoLYlVTYkGER5h4RlSWzBE6xgd3g/edit#heading=h.ap3hp158d2we)to support the Open Source factor of our project. This body of work focuses on incorporating that content into our Grants Equity repo in sections such as, [README.md](https://github.com/HHS/grants-equity/blob/main/README.md), [CONTRIBUTING.md](https://github.com/HHS/grants-equity/blob/main/CONTRIBUTING.md).

This ticket is updating the Grants Equity repo README with the [README](https://docs.google.com/document/d/1CyoA57KejbNEGhaLoLYlVTYkGER5h4RlSWzBE6xgd3g/edit#bookmark=id.d3gpx7y17a2p) section from the OS runbook. 

### Acceptance criteria

- [ ] Review the content in the [README](https://docs.google.com/document/d/1CyoA57KejbNEGhaLoLYlVTYkGER5h4RlSWzBE6xgd3g/edit#bookmark=id.d3gpx7y17a2p) and update the content to make relevant for the Grants Equity project where needed
- [ ] Add content in the [Grants Equity README](https://github.com/HHS/grants-equity/blob/main/README.md)

**Comment by acouch** [comment]
I've started this https://github.com/HHS/grants-equity/tree/acouch/issue-402-update-readme-usdr

**Comment by andycochran** [comment]
Moving this here from the duplicate issue… 

Currently, the `README` in the root directory is missing information under the first 5 headings. 

It would be helpful if this `README` included an easy-to-find link to the milestones right up front. Beta site users are told to "read our project goals and milestones" and should be able to easily find them from the [github.com/HHS/grants-equity](https://github.com/HHS/grants-equity/) URL. 
 
![image](https://github.com/HHS/grants-equity/assets/409279/d40e955d-dc68-4746-95d3-2d3cb57ef2e9)

Perhaps the `README` should also link back to beta site (once we have a URL pointed).
