### ISSUE TITLE
[Task]: Determine Up-time monitoring tool, alerts, and alert recipients for static site

### ISSUE THREAD

**Issue by acouch** [HHS/grants-equity#413]
## Tool

I would imagine that [cloudwatch synthetics](https://repost.aws/knowledge-center/cloudwatch-synthetics-performance) would be the preferred implementation, but that can be determined during the completion of the ticket.

## Alerts

I would imagine we would want one that pings the site frequently, returns the status code, and a text string to determine that the site is up. We could also setup alerts for health checks on the container.

We could potentially use the same alerts to provide metrics like overall up-time and site speed, but that is outside the scope of this.

## Recipients

This would likely be individuals by email, phone, and / or a slack channel. This would likely be part of the IRP. This part of the task could be removed if it is determined that it is better to handle this in the IRP. This list should not be public.

### Acceptance criteria

- [ ] Tool for up-time monitoring determined
- [ ] List of alerts determined
- [ ] Recipients determined, but not publicly shared.

**Comment by acouch** [comment]
This is a useful resource https://github.com/navapbc/template-infra/pull/359

**Comment by sumiat** [comment]
not needed
