### ISSUE TITLE
Milestone: Onboard development team

### ISSUE THREAD

**Issue by widal001** [HHS/grants-equity#44]
### Description

Have the software development team for this effort start their work and get systems access.

### Teams Involved

- HHS 
- MicroHealth

### Sub-Tasks

- [x] #139 

### Definition of Done

- The grants.gov modernization team has appropriate systems access

**Comment by sumiat** [comment]
Team has access to their own AWS environment, Git and other tools for software eng dev cycle which is appropriate to onboard the team.
