### ISSUE TITLE
[Task]: Upgrade to GitBook Pro Plan & confirm Slack plan

### ISSUE THREAD

**Issue by widal001** [HHS/grants-equity#442]
### Summary

Work with the MH team to upgrade our GitBook trial instance to a Pro Plan before our free trial expires on 9/11/23.

### Acceptance criteria

- [x] Our GitBook instance has been upgraded to the pro plan
- [x] We can add new members to our GitBook instance without re-negotiating a contract
- [x] The content we drafted during the trial period is still available in the upgraded plan

**Comment by sarahknoppA6** [comment]
Set a meeting for 9/5 at 3:30 EDT with MicroHealth to discuss.

**Comment by widal001** [comment]
MH upgraded us to the Pro plan on 9/7/23


![Image](https://github.com/HHS/grants-equity/assets/21350331/ac6801b2-2069-4579-a0ad-09092ed91bfd)
