### ISSUE TITLE
[ADR]: Unconference tools for Team of Teams

### ISSUE THREAD

**Issue by sarahknoppA6** [HHS/grants-equity#455]

**Comment by sarahknoppA6** [comment]
@lucasmbrown-usds Here's what I'm thinking for the Team of Teams + Open Discussion. Feel free to add comments! 
https://docs.google.com/document/d/1q675AtqOaj9RtGjOw6P1pRG5CspXr6zNdBZxiyB0BI0/edit?usp=sharing

**Comment by widal001** [comment]
Having first ToT today
