### ISSUE TITLE
[Task] Agenda and Unconf Board for ToT + Open Discussion

### ISSUE THREAD

**Issue by sarahknoppA6** [HHS/grants-equity#460]

**Comment by sarahknoppA6** [comment]
@lucasmbrown-usds Here's what I'm thinking for ToT and Open Discussion next week.
https://docs.google.com/document/d/1q675AtqOaj9RtGjOw6P1pRG5CspXr6zNdBZxiyB0BI0/edit?usp=sharing

**Comment by widal001** [comment]
First ToT happening today
