### ISSUE TITLE
[Epic]: CMS Planning  

### ISSUE THREAD

**Issue by sumiat** [HHS/grants-equity#461]
### Summary

We want to understand if beta.grants.gov will need a content management system (CMS). Some considerations are whether we need the CMS now or if it should be implemented later. In this work, we will evaluate the 

### Sub-tasks
- [ ] #462
- (dependent on the above) ADR of what the CMS should be 

### Acceptance criteria

- Decision on whether the project will use a CMS and what next steps are.

**Comment by widal001** [comment]
@sumiat I think this is a duplicate of #75

**Comment by sumiat** [comment]
yes, it is! will close it out.
