### ISSUE TITLE
[Task] Create a CSR for beta

### ISSUE THREAD

**Issue by sumiat** [HHS/grants-equity#472]
To get an SSL certificate, we need to complete the [DNS_Change_Request.pdf](https://github.com/HHS/grants-equity/files/12529419/DNS_Change_Request.pdf). We should create a Certificate Signing Request in preparation for the DNS change request.

Blocked by #295 

**Acceptance Criteria**
- [x] Create a Certificate Signing Request for our own environment that we share with Terrence and/or Oscar

**Comment by SammySteiner** [comment]
@acouch Just sent the CSR to HHS with the DNS request.
