### ISSUE TITLE
[Task]: Increase Fargate Instance Count to 2 for frontend

### ISSUE THREAD

**Issue by acouch** [HHS/grants-equity#520]
### Summary

Increase the instance count for the ECS Fargate tasks in frontend cluster to 2.

### Acceptance criteria

- [ ] desired instance count set to 2

**Comment by daphnegold** [comment]
I got this 😆

**Comment by daphnegold** [comment]
I'd also like to just quickly check what the recommended CPU and memory is for a simple web app, since we will be in there modifying desired instance count.
