### ISSUE TITLE
Simpler.grants.gov domain request

### ISSUE THREAD

**Issue by sumiat** [HHS/grants-equity#543]
### Description

Our project name has changed and we should update the URL to Simpler Grants.gov. We want to change the URL to simpler.grants.gov. 

### Acceptance Criteria

- [ ] Request simpler.grants.gov domain 
- [ ] Hook up simpler.grants.gov domain 
- [ ] Redirect beta.grants.gov to simpler.grants.gov

**Comment by acouch** [comment]
Apologies, I hadn't seen this when I created some additional tickets. I split the task up into several items in the milestone: https://github.com/HHS/grants-equity/milestone/90
