### ISSUE TITLE
[Task]: Update milestone doc for GET Opportunities

### ISSUE THREAD

**Issue by widal001** [HHS/grants-equity#560]
### Summary

Update the GET Opportunities milestone doc to remove references to prescriptive requirements (e.g. the API endpoint root path `beta.grants.gov/api`)

### Acceptance criteria

- [ ] Updates have been made to the GET Opportunities milestone doc and reviewed by the team

**Comment by sarahknoppA6** [comment]
waiting on PR from Aaron and Sumi

**Comment by sumiat** [comment]
Added here: https://github.com/HHS/grants-equity/pull/577
