### ISSUE TITLE
[Task]: Write GitBook content guidelines for public/private forums

### ISSUE THREAD

**Issue by lucasmbrown-usds** [HHS/grants-equity#571]
### Description

Create a page within GitBook that provides guidelines for posting in public & private forums

### Definition of Done

- [ ] A wiki page with posting guidelines has been created
- [ ] That page has been reviewed by @lucasmbrown-usds 
- [ ] An export of that page has been shared with internal stakeholders

**Comment by widal001** [comment]
Private content includes:

- PII
- Credentials
- Budget
- Anything specific to Simpler NOFOs workstream
- Personnel
- Dates or deadlines - with a provisional caveat
- ODCs

**Comment by widal001** [comment]
Here are the two docs related to this task:

- [How do we communicate](https://app.gitbook.com/o/cFcvhi6d0nlLyH2VzVgn/s/v1V0jIH7mb7Yb3jlNrgk/collaborating/how-we-communicate)
- [Content guidelines](https://app.gitbook.com/o/cFcvhi6d0nlLyH2VzVgn/s/v1V0jIH7mb7Yb3jlNrgk/collaborating/how-we-communicate/content-privacy-guidelines)
