### ISSUE TITLE
[Epic]: Front-end CI/CD

### ISSUE THREAD

**Issue by widal001** [HHS/grants-equity#58]
### Description

Install developer tools for front-end, including:

- Automated test framework
- Linters, code quality checkers, and code autoformatters
- Automated test coverage analysis
- Security scan of packages (Snyk or alternative)
- Automated accessibility testing
- Mobile responsiveness testing
- Funding needs of packages (https://backyourstack.com/ or alternative)

### Dependencies

- [x] #49 
- [x] #50 
- [ ] #53 

### Sub-Tasks

- [x] #185 
- [x] Configure GH workflows to facilitate creating releases for production
- [x] Dev and prod environment

### Definition of Done
- Dev environment are deployed form a `main` branch 
- Prod environment deployed from workflow

**Comment by sumiat** [comment]
work for this for beta is complete
