### ISSUE TITLE
[Task]: Connect to lower env database (app)

### ISSUE THREAD

**Issue by acouch** [HHS/grants-equity#603]
### Summary

The API in both the prod and dev environments in our current non-production AWS account, should connect to the lower environment database.

There is are `api-dev-primary` and `api-prod-primary` instances already created in our AWS account.

This ticket is to do this on application end.

### Acceptance criteria

- [x] API has database connection in dev/prod environments
- [x] Query the healthcheck endpoint and confirm we get a 200 [api-dev-928241344.us-east-1.elb.amazonaws.com](http://api-dev-928241344.us-east-1.elb.amazonaws.com/health)

### Open Questions / Notes
- If the DMS is not there, health check endpoint only is OK? Yes
- Flask API is connected to deployed db in AWS; locally - would need to connect via IAM roles; connects via role manager rather than credentials
- Do we want to create a second db or create an app db? We decided to reuse our current one. 
- connecting locally would be setting the credentials locally/ individually.

**Comment by sumiat** [comment]
Closed as a dupe
