### ISSUE TITLE
[Epic]: Web analytics

### ISSUE THREAD

**Issue by widal001** [HHS/grants-equity#63]
### Description

Choose and implement a web analytics framework, such as analytics.usa.gov or Google Analytics, where all data can be made publicly available.

### Dependencies

- [x] #49 
- [ ] #60 

### Sub-Tasks

- [X] #372 
- [x] #389 
- [x] Register for an analytics ID from DAP or HHS 

### Definition of Done

The Digital Analytics Program tag for analytics.usa.gov is set up on the static beta.grants.gov site to have basic tracking. Enhanced events are set up so that we can track scrolling and PDF clicks and downloads.

**Comment by lucasmbrown-usds** [comment]
Will need an ADR on Google Analytics vs analytics.usa.gov. According to https://digital.gov/guides/dap/add-your-site-dap/, participating in the analtyics.usa.gov is mandatory for all public-facing websites. But we could potentially have both if there's something not available in analytics.usa.gov that we can access by directly managing Google Analytics.

**Comment by sumiat** [comment]
completed and analytics running on beta
