### ISSUE TITLE
[Epic]: Internationalization framework

### ISSUE THREAD

**Issue by widal001** [HHS/grants-equity#64]
### Description

TODO

### Dependencies

- [x] #49 
- [ ] #75 

### Sub-Tasks

TODO

### Definition of Done

TODO

**Comment by lucasmbrown-usds** [comment]
Let's check in with @andycochran and @acouch et al to see about the right order of operations for this. Does it make sense to build the i18n framework into the foundational UI before we add any other content? Sometimes it's harder to add i18n later to an existing site. But I defer to y'all!

**Comment by andycochran** [comment]
Very likely we can get this one for free. Tho we haven't discussed frontend planning with the group yet, one solution Nava has been thinking of and discussing internally would include i18n out-of-the-box.

**Comment by acouch** [comment]
@lucasmbrown-usds We have a template that includes [Next.js i18n routing](https://nextjs.org/docs/pages/building-your-application/routing/internationalization). Agree it would be preferable to include that in the initial front-end setup #110 .

**Comment by lucasmbrown-usds** [comment]
Awesome, great news @andycochran @acouch !

**Comment by acouch** [comment]
We have adopted an i18n library for the front-end. It is documented here: https://github.com/HHS/grants-equity/blob/main/documentation/frontend/internationalization.md
